### ISSUE TITLE
n_correct, n_correct fraction and n_samples meaning in FullModelTest.py

### ISSUE THREAD

**Issue by ankur219** [vl2g/VRC#3]
Hi,
First of all congratulations on the paper.
I have tried to run your code. And while I was going through FullModelTest.py, I couldn't understand what n_correct, n_correct fraction, and n_samples mean. How do we compute bag-corloc and VR-corloc from these numbers?

**Comment by vaibhavmishra1** [comment]
n_correct  = bag_corloc
n_correct fraction = VR-Corloc

**Comment by ankur219** [comment]
Thanks for your comment.
When I ran your code, these are the numbers I received:

dataset_length= 16
n_correct= 10
n correct fraction= 12.0
n_samples= 16

The bag_corloc I suppose is then n_correct/n_samples = 62.5
And the VR_corloc is n_correct_fraction/n_samples = 75.

The numbers in the paper are, however, 63.40 and 78.99 respectively. I hope the way to calculate bag_corloc and vr_corloc is correct or am I doing something wrong since there is some difference in the numbers.

Thanks

**Comment by vaibhavmishra1** [comment]
Hi ankur,
your results are correct.
During training and testing, the dataset is sampled randomly from a set of examples during training as well as testing so you may not get the exact results. please consider a deviation of +-8%.

**Comment by ankur219** [comment]
Thanks for the help!
